export interface Product {
  id: string
  name: string
  price: number
  image: string
  roastLevel: "Light" | "Medium" | "Dark"
  origin: string
  category: "beans" | "capsules" | "equipment" | "accessories"
  description: string
  strength: number
  notes: string[]
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Ethiopian Yirgacheffe",
    price: 24,
    image: "coffee-1",
    roastLevel: "Light",
    origin: "Ethiopia",
    category: "beans",
    description: "Floral and tea-like with berry undertones",
    strength: 3,
    notes: ["Floral", "Berry", "Tea-like"],
  },
  {
    id: "2",
    name: "Colombian Supremo",
    price: 22,
    image: "coffee-2",
    roastLevel: "Medium",
    origin: "Colombia",
    category: "beans",
    description: "Balanced with chocolate and nutty notes",
    strength: 5,
    notes: ["Chocolate", "Nutty", "Balanced"],
  },
  {
    id: "3",
    name: "Brazilian Santos",
    price: 20,
    image: "coffee-3",
    roastLevel: "Dark",
    origin: "Brazil",
    category: "beans",
    description: "Rich and smooth with caramel sweetness",
    strength: 7,
    notes: ["Caramel", "Smooth", "Sweet"],
  },
  {
    id: "4",
    name: "Kenya Peaberry",
    price: 28,
    image: "coffee-4",
    roastLevel: "Medium",
    origin: "Kenya",
    category: "beans",
    description: "Bright acidity with black currant notes",
    strength: 6,
    notes: ["Bright", "Black Currant", "Citrus"],
  },
  {
    id: "5",
    name: "Sumatra Mandheling",
    price: 26,
    image: "coffee-5",
    roastLevel: "Dark",
    origin: "Indonesia",
    category: "beans",
    description: "Full-bodied with earthy and herbal notes",
    strength: 8,
    notes: ["Earthy", "Herbal", "Spicy"],
  },
  {
    id: "6",
    name: "Guatemala Antigua",
    price: 25,
    image: "coffee-6",
    roastLevel: "Medium",
    origin: "Guatemala",
    category: "beans",
    description: "Complex flavor with smoky and spicy notes",
    strength: 6,
    notes: ["Smoky", "Spicy", "Complex"],
  },
  {
    id: "7",
    name: "Espresso Capsules - 10 Pack",
    price: 12,
    image: "capsule-1",
    roastLevel: "Dark",
    origin: "Mixed Origins",
    category: "capsules",
    description: "Premium espresso capsules compatible with most machines",
    strength: 7,
    notes: ["Rich", "Bold", "Convenient"],
  },
  {
    id: "8",
    name: "Lungo Capsules - 10 Pack",
    price: 12,
    image: "capsule-2",
    roastLevel: "Medium",
    origin: "Mixed Origins",
    category: "capsules",
    description: "Smooth lungo coffee capsules for everyday brewing",
    strength: 5,
    notes: ["Smooth", "Daily", "Convenient"],
  },
  {
    id: "9",
    name: "Pour Over Dripper",
    price: 18,
    image: "equipment-1",
    roastLevel: "Light",
    origin: "N/A",
    category: "equipment",
    description: "Ceramic pour over cone for perfect brewing",
    strength: 0,
    notes: ["Ceramic", "Precision", "Manual"],
  },
  {
    id: "10",
    name: "Burr Grinder Pro",
    price: 89,
    image: "equipment-2",
    roastLevel: "Light",
    origin: "N/A",
    category: "equipment",
    description: "Stainless steel burr grinder with 15 grind settings",
    strength: 0,
    notes: ["Precision", "Durable", "Professional"],
  },
]
